substitutions:
  name: "sonoff-s31"
  friendly_name: "Sonoff S31"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: "CloudFree.S31"
    version: "1.0.0"
esp8266:
  board: esp07s

logger:
  baud_rate: 0

api:

ota:

web_server:
  local: true

text_sensor:
  - platform: wifi_info
    ip_address:
      name: $friendly_name IP Address

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${name} Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "${name} Status"

sensor:
  - platform: wifi_signal
    name: "${name} WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    current:
      name: "${name} Current"
      accuracy_decimals: 1
    voltage:
      name: "${name} Voltage"
      accuracy_decimals: 1
    power:
      name: "${name} Power"
      accuracy_decimals: 1
      id: my_power
  - platform: total_daily_energy
    name: "${name} Daily Energy"
    power_id: my_power

switch:
  - platform: gpio
    name: "${name} Relay"
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF

time:
  - platform: sntp
    id: my_time

status_led:
  pin:
    number: GPIO13
    inverted: True

dashboard_import:
  package_import_url: github://CloudFreeShop/esphome-templates/sonoff-s31.yaml
  import_full_config: false

wifi:
  ap:

captive_portal:
